### ISSUE TITLE
pki client must prove ownership of curve25519 private key

### ISSUE THREAD

**Issue by david415** [applied-mixnetworks/pymixpki#1]
currently the keyserver crypto protocol doesn't enforce that the client has the private curve25519 key. i think this could lead to security problems depending on how the keyserver is implemented. correct?

an easy solution is to use the decisional Diffie-Hellman assumption to compute a shared secret:

1. get 32 bytes of shared data and turn them into a curve25519 point. call it our blind_factor
2. compute our alpha value where alpha = scalar_mult(generator, blind_factor)
3. dh_value = scalar_mult(alpha, private_key)

to verify:

1. assert dh_value == scalar_mult(public_key, blind_factor)

**Comment by burdges** [comment]
I'll try to read the spec over the weekend.  I'd use another term for blinding factor since normally that's a secret scalar not a public point.  I'm not sure what you mean by multiplying the generator by another point, but maybe you mean the blinding_factor is a scalar?  I'm not seeing why your dh_value proves anything?

I think the routing private key could just sign it's own certificate, although you translate between different curve forms then.

There are also schemes involving a hash function H that produces curve points so that *nobody* knows the scalar for which they correspond.  You cannot just produce 32 byes and zero the high bit here because not all elements of that form are points on the curve, but if I recall correctly then half are points on the curve, so you can just produce a succession with shake or chacha, check each to see if it's a point on the curve, and use it if so.  It might be the others are points on the twist which might be okay too.  

I think hashing to the curve mostly crops up with pairing though.  I can make up signature like schemes that use it, but maybe just using a signature is easier.

**Comment by david415** [comment]
the dh_value proves that the client controls the private curve25519 key.
the other party can see this by computing the shared secret using the client's public curve25519 key.

here's a concise example of this right here in this test_ed25519_decisional_diffiehellman_assumption unit test i wrote the other day:

https://github.com/applied-mixnetworks/sphinxmixcrypto/blob/master/tests/test_crypto_primitives.py#L32-L33

**Comment by burdges** [comment]
If I understand, the client knows the blind_factor, so they can just use that instead of private_key, like the verifier does, no?

**Comment by david415** [comment]
oh right. so in order for this to work the client would have to receive a blinded value from the server, unblind it using the private curve25519 key and then send this unblinded value back to the server as the key vouch.

**Comment by david415** [comment]
hmm but we wouldn't want this to expose the client as a decryption oracle... which is what it would do ;-p

**Comment by david415** [comment]
ok i've removed that stuff from the spec. perhaps one of those transformations curve25519 -> ed25519 would have the properties i need? could the public key be transformed to ed25519 without knowledge of the private key material?

**Comment by burdges** [comment]
I think a signature with the routing key will do this just fine, but that does require starting from an Edwards curve point, and converting to Montgomery, or else using Trever's VXEd25519 stuff. 

Yes, you can convert them.  AGL's go library for Ed25519 does it in a module called extra25519.go.  

I'm still not completely sure I understand the threat model there.
